### ISSUE TITLE
Pin the OTP version in the mix commands

### ISSUE THREAD

**Issue by mariari** [anoma/green#86]
customer: @mariari
performer:
deadline: null
estimated: null
started: null
actual: null
completed: null
confirmed: null
dependencies:
- [ ]

---

Currently we set it up in the CI as follows

```yaml
    - name: Set up Elixir
      id: beam
      if: steps.try_merge.outcome != 'failure'
      uses: erlef/setup-beam@v1.16.0
      with:
        elixir-version: '1.15.6'
        otp-version: '26.1.2'
```

However it would be good if we pinned it in the mix commands which do not have it pinned 

```yaml
    - name: Run tests
      if: steps.try_merge.outcome != 'failure'
      run: mix test
```
